title: Researcher
url: "https://li-cr.github.io/show"
baseurl: "/researcher"

remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: Last modified: {{ site.time | date: "%b %d, %Y" }}

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
